<a href="https://colab.research.google.com/github/YasserPR91/NewSkills/blob/main/COOP_SQL_Murder_Mystery.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# SQL Murder Mystery!
Adapted By: Martin Arroyo

![Detective making connections between points](https://github.com/freestackinitiative/coop_sql_notebooks/blob/v2/assets/sleuth.png?raw=1)

**Credit**

This material was adapted from the [SQL Murder Mystery by Knight Lab](https://mystery.knightlab.com/) under [Creative Commons CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/). The SQL Murder Mystery was originally created by [Joon Park](https://twitter.com/joonparkmusic) and [Cathy He](https://twitter.com/Cathy_MeiyingHe) while they were Knight Lab fellows. See the [GitHub repository](https://github.com/NUKnightLab/sql-mysteries) for more information.

## Scenario

A crime has taken place and detectives need your help! You were given the crime scene report, but you somehow lost it. You vaguely remember that the crime was a `​murder`​ that occurred sometime on `​January 15, 2018`​ and that it took place in ​`SQL City`​. It is up to you to find out who the murderer is using just your SQL skills and resourcefulness. You are given a connection to the Police Department's database which has all of the clues you'll need to track down the killer.

Use the skills you developed in SQL 101 and 102, along with any resources you like, to solve the `SQL Murder Mystery`!

## Connect to the Police Department Database

To get started and run your queries, press play in the cell below to connect to the Police Department database.

To run queries, create a new `Code` cell and write `%%sql` at the top of it. Then you can write your queries underneath. See the example below:
```python
%%sql

SELECT *
FROM table

```

In [ ]:
%%capture --no-stderr
# @title Press Play { display-mode: "form" }
# Install `teachdb` and `coop_grader`
print("Installing `teachdb` and its dependencies...")
%pip install --quiet --upgrade git+https://github.com/freestackinitiative/teachingdb.git git+https://github.com/martinmarroyo/coop_grader.git
print("Successfully installed `teachdb`")
from teachdb.teachdb import connect_teachdb
from coop_grader.sql_murder_mystery.check_suspect import check_suspect
# Set configurations for notebook & load data
con = connect_teachdb(database="sql_murder_mystery")

%sql con

## Discovering tables in the database

We start our quest to find the murderer by exploring the Police Department database. But you haven't seen the database yet, and you don't know what the tables are, so how do you know what to look for?

Thankfully, most relational database management systems have this information stored in a place where you can query it. Very often, a special schema known as the [`information_schema`](https://en.wikipedia.org/wiki/Information_schema) is used to store information about the tables and columns in your database (aka metadata.) The police department's database has an information schema, with the `tables` view showing you what tables are available, and the `columns` view which shows you all the columns for each table and their data types.

### Listing all the tables in the Police Database

#### Check the [`information_schema.tables` description](https://duckdb.org/docs/sql/information_schema.html#tables-and-views)

First, we'll look at all the tables available to us by checking the `information_schema.tables` view. We'll give you the first query to start, but from here on out you will have to come up with the remaining queries using your SQL knowledge and your resourcefulness.

Here is the query that is needed to show you the tables in the Police Department Database. Copy/Paste it into the cell below and run it to see the tables available to you:

>```sql
>SELECT *
>FROM information_schema.tables
>```

In [ ]:
%%sql

SELECT *
FROM information_schema.tables

,table_catalog,table_schema,table_name,table_type,self_referencing_column_name,reference_generation,user_defined_type_catalog,user_defined_type_schema,user_defined_type_name,is_insertable_into,is_typed,commit_action,TABLE_COMMENT
0,memory,main,crime_scene_report,BASE TABLE,None,None,None,None,None,YES,NO,None,None
1,memory,main,drivers_license,BASE TABLE,None,None,None,None,None,YES,NO,None,None
2,memory,main,facebook_event_checkin,BASE TABLE,None,None,None,None,None,YES,NO,None,None
3,memory,main,get_fit_now_check_in,BASE TABLE,None,None,None,None,None,YES,NO,None,None
4,memory,main,get_fit_now_member,BASE TABLE,None,None,None,None,None,YES,NO,None,None
5,memory,main,income,BASE TABLE,None,None,None,None,None,YES,NO,None,None
6,memory,main,interview,BASE TABLE,None,None,None,None,None,YES,NO,None,None
7,memory,main,person,BASE TABLE,None,None,None,None,None,YES,NO,None,None

### Listing all the tables and their columns in the Police Database

**Check the [`information_schema.columns` description](https://duckdb.org/docs/sql/information_schema.html#columns)**

Great! Now that you know what tables are available, it's time to find out the columns that each table has along with the data type of each column. Write a query that shows the table name, column name, and data type for each table in the Police Department database using the `information_schema.columns` view. Make sure that the output is ordered by table, then column name (ascending):

*Optional hints - try to only use them if you get **REALLY** stuck!*

<details>
<summary>Hint 1</summary>
<p>Structure your query just like we did in the previous one where we looked at `information_schema.tables`</p>
</details>

<details>
<summary>Hint 2</summary>
<p>Make sure to check the link for the information_schema.columns description! It will tell you the column names that you should use for the query. Remember, we want the table name, column name, and data type - check the description to find the appropriate names!</p>
</details>

<details>
<summary>Hint 3</summary>
<p>Don't forget to use the ORDER BY statement to order your search results. We are looking to sort both columns in ascending order, which can be specified using the ASC keyword, however, it is also the default sort order, so ASC is not necessarily required.</p>
</details>

In [ ]:
%%sql
SELECT table_name, column_name, data_type
FROM information_schema.columns
ORDER BY table_name, column_name ASC

                table_name            column_name data_type
0       crime_scene_report                   city   VARCHAR
1       crime_scene_report                   date   INTEGER
2       crime_scene_report            description   VARCHAR
3       crime_scene_report                   type   VARCHAR
4          drivers_license                    age   INTEGER
5          drivers_license               car_make   VARCHAR
6          drivers_license              car_model   VARCHAR
7          drivers_license              eye_color   VARCHAR
8          drivers_license                 gender   VARCHAR
9          drivers_license             hair_color   VARCHAR
10         drivers_license                 height   INTEGER
11         drivers_license                     id   INTEGER
12         drivers_license           plate_number   VARCHAR
13  facebook_event_checkin                   date   INTEGER
14  facebook_event_checkin               event_id   INTEGER
15  facebook_event_checkin             event_name   VARCHAR
16  facebook_event_checkin              person_id   INTEGER
17    get_fit_now_check_in          check_in_date   INTEGER
18    get_fit_now_check_in          check_in_time   INTEGER
19    get_fit_now_check_in         check_out_time   INTEGER
20    get_fit_now_check_in          membership_id   VARCHAR
21      get_fit_now_member                     id   VARCHAR
22      get_fit_now_member  membership_start_date   INTEGER
23      get_fit_now_member      membership_status   VARCHAR
24      get_fit_now_member                   name   VARCHAR
25      get_fit_now_member              person_id   INTEGER
26                  income          annual_income   INTEGER
27                  income                    ssn   INTEGER
28               interview              person_id   INTEGER
29               interview             transcript   VARCHAR
30                  person         address_number   INTEGER
31                  person    address_street_name   VARCHAR
32                  person                     id   INTEGER
33                  person             license_id   INTEGER
34                  person                   name   VARCHAR
35                  person                    ssn   INTEGER

### Entity Relationship Diagram (Optional)

After doing some detective work and finding the tables in the Police Department database, you discover that there is an ERD! This can be really helpful in your quest to find the murderer. If you like, challenge yourself (and your SQL skills) to continue on by just querying the `information_schema` as needed. Otherwise, you can click the dropdown below to reveal the ERD to help you see the tables and relationships in the Police Department database at a glance:

<details>
  <summary>Check the SQL Murder Mystery ERD</summary>
  <img src="https://github.com/freestackinitiative/coop_sql_notebooks/blob/v2/assets/murder_mystery_schema.png?raw=1" alt="ERD for SQL Murder Mystery"/>
</details>

## Beginning your investigation

Start by retrieving the corresponding crime scene report from the police department’s database.

<details>
<summary>Clue #1</summary>
<p>Look at the tables available in the Police Department database. Could the crime scene report be in there?</p>
</details>

<details>
<summary>Clue #2</summary>
<p>The murder occured on January 15, 2018 in SQL City. Perhaps filtering your query with this information can help you find that crime report you're looking for...</p>
</details>

In [ ]:
%%sql

SELECT date, type, description, city
FROM crime_scene_report
WHERE Date = 20180115 AND Type = 'murder' AND city = 'SQL City'

,date,type,description,city
0,20180115,murder,Security footage shows that there were 2 witnesses. The first witness lives at the last house o...,SQL City

___

## Solving the Mystery (and checking if you cracked the case!)

From here on out, you'll be using your skills and the clues in the Police Department database to find the killer. When you think you have found the killer, come back to this section and use the cell below to check your answer and see if you found the murderer:

ex:
```python
check_suspect("Adam Levine")
```

In [ ]:
check_suspect("Miranda Priestly")

Congrats, you found the brains behind the murder!
Everyone in SQL City hails you as the greatest SQL detective of all time.
Time to break out the champagne!

True

---

## Workspace

Use the cells below to write your queries and work on solving the mystery. When you have a suspect, check your answer using the [cell above this one](#solving-the-mystery-and-checking-if-you-cracked-the-case) and running their name through the `check_suspect` function. If you find the murderer, the function will tell you.

Don't forget to use `%%sql` at the top of the `Code` cells you create in order to get your SQL queries to work. Good luck, sleuths!

In [ ]:
%%sql

SELECT *
FROM person
WHERE address_street_name = 'Northwestern Dr'
ORDER BY address_number DESC

       id                  name  license_id  address_number address_street_name        ssn
0   14887        Morty Schapiro      118009            4919     Northwestern Dr  111564949
1   17729        Lasonya Wildey      439686            3824     Northwestern Dr  917817122
2   53890        Sophie Tiberio      957671            3755     Northwestern Dr  442830147
3   73368        Torie Thalmann      773862            3697     Northwestern Dr  341559436
4   96595         Coretta Cubie      303645            3631     Northwestern Dr  378403829
5   19420           Cody Schiel      890431            3524     Northwestern Dr  947110049
6   93509        Emmitt Aceuedo      916706            3491     Northwestern Dr  979073160
7   87456   Leonora Wolfsberger      215868            3483     Northwestern Dr  565203106
8   36378        Freddie Ellzey      267882            3449     Northwestern Dr  474117596
9   53076           Boris Bijou      664914            3327     Northwestern Dr  401191868
10  28360        Rashad Cascone      924517            3212     Northwestern Dr  838907424
11  23044          Val Portlock      924989            3143     Northwestern Dr  100593316
12  51114     Christena Saffell      814284            3055     Northwestern Dr  247657547
13  68690            Yer Modest      852404            3046     Northwestern Dr  419238039
14  44004           Alison Eska      327797            2951     Northwestern Dr  306417867
15  98593           Jonah Toner      578982            2947     Northwestern Dr  745853548
16  59307          Cyril Yongue      753524            2903     Northwestern Dr  866057839
17  34155      Allyson Lazenson      814209            2840     Northwestern Dr  991150469
18  90397     Dionna Kranwinkle      797260            2678     Northwestern Dr  278964807
19  54564         Sammie Sengun      217286            2590     Northwestern Dr  848854310
20  53699      Christian Pagano      628433            2585     Northwestern Dr  644772304
21  34352    Vincenza Burkhardt      436470            2512     Northwestern Dr  197913046
22  80921       Donovan Yackley      222395            2386     Northwestern Dr  515049359
23  96178           Galina Khuu      450248            2183     Northwestern Dr  398518185
24  81885         Kurtis Masuda      934201            2108     Northwestern Dr  201272595
25  88423           Teri Ehrich      510876            1879     Northwestern Dr  248637345
26  51552           Bonita Knie      764124            1726     Northwestern Dr  597137908
27  72076     Courtney Bordeaux      324614            1707     Northwestern Dr  347966356
28  81052     Calvin Czelusniak      471483            1516     Northwestern Dr  657531837
29  71924        Laurie Scronce      774116            1418     Northwestern Dr  254883636
30  23960  Kristopher Lagerberg      658777            1392     Northwestern Dr  492912529
31  70485     Andera Kostelecky      354822            1252     Northwestern Dr  787423012
32  22239         Dusty Sigafus      710517            1125     Northwestern Dr  724386723
33  18376              Josh Shi      653712            1091     Northwestern Dr  193899001
34  29608       Willetta Lurvey      800568            1028     Northwestern Dr  843751378
35  33415         Homer Simpson      108392             981     Northwestern Dr  871392019
36  55130        Shiloh Huntoon      472118             951     Northwestern Dr  826647644
37  44542        Ivory Mcgrevey      873842             897     Northwestern Dr  988557407
38  99826          Ivy Kazarian      994470             892     Northwestern Dr  208359813
39  25615         Olevia Morena      388477             812     Northwestern Dr  962831331
40  40760          Renata Faver      976650             745     Northwestern Dr  547572040
41  10010             Muoi Cary      385336             741     Northwestern Dr  828638512
42  39688            Abe Roeker      537445             689     Northwestern Dr  438969447
43  26758      Angelena Billman      942074             629     Northwestern Dr  341854756
44  75484          Del Tacderen      447887             607     Northwestern Dr  243821337
45  12711        Norman Apolito      667757             599     Northwestern Dr  778264744
46  85280             Donn Duin      569122             540     Northwestern Dr  613873810
47  40336       Fredia Billeter      251082             404     Northwestern Dr  108056488
48  15171          Weldon Penso      336999             311     Northwestern Dr  131379495
49  89906       Kinsey Erickson      510019             309     Northwestern Dr  635287661

In [ ]:
%%sql

SELECT *
FROM Person
WHERE address_street_name = 'Franklin Ave' and name LIKE 'Annabel%'

      id            name  license_id  address_number address_street_name        ssn
0  16371  Annabel Miller      490173             103        Franklin Ave  318771143

In [ ]:
%%sql

SELECT *
FROM interview
WHERE person_id = 16371 OR person_id = 14887

,person_id,transcript
0,16371,"I saw the murder happen, and I recognized the killer from my gym when I was working out last we..."
1,14887,"I heard a gunshot and then saw a man run out. He had a ""Get Fit Now Gym"" bag. The membership nu..."

In [ ]:
%%sql

SELECT *
FROM get_fit_now_check_in
WHERE membership_id LIKE '48Z%' AND check_in_date = 20180109
order by check_in_date

  membership_id  check_in_date  check_in_time  check_out_time
0         48Z7A       20180109           1600            1730
1         48Z55       20180109           1530            1700

In [ ]:
%%sql

SELECT *
FROM drivers_license
WHERE gender = 'male' AND plate_number LIKE '%H42W%'

       id  age  height eye_color hair_color gender plate_number   car_make car_model
0  423327   30      70     brown      brown   male       0H42W2  Chevrolet  Spark LS
1  664760   21      71     black      black   male       4H42WR     Nissan    Altima

In [ ]:
%%sql

SELECT *
FROM person
WHERE license_id = 423327 OR license_id = 664760

      id            name  license_id  address_number    address_street_name        ssn
0  51739  Tushar Chandra      664760             312                 Phi St  137882671
1  67318   Jeremy Bowers      423327             530  Washington Pl, Apt 3A  871539279

In [ ]:
%%sql

SELECT *
FROM get_fit_now_member
WHERE person_id = 51739 OR person_id = 67318

      id  person_id           name  membership_start_date membership_status
0  48Z55      67318  Jeremy Bowers               20160101              gold

In [ ]:
%%sql

SELECT *
FROM interview
WHERE person_id = 67318

,person_id,transcript
0,67318,"I was hired by a woman with a lot of money. I don't know her name but I know she's around 5'5"" ..."

In [ ]:
%%sql

SELECT *
FROM drivers_license
WHERE gender = 'female'
  AND hair_color = 'red'
  AND height BETWEEN '65' AND '67'
  AND car_make = 'Tesla'
  AND car_model = 'Model S'

       id  age  height eye_color hair_color  gender plate_number car_make car_model
0  202298   68      66     green        red  female       500123    Tesla   Model S
1  291182   65      66      blue        red  female       08CM64    Tesla   Model S
2  918773   48      65     black        red  female       917UU3    Tesla   Model S

In [ ]:
%%sql

SELECT *
FROM person
WHERE license_id = 202298 OR license_id = 291182 OR license_id = 918773

      id              name  license_id  address_number address_street_name        ssn
0  78881          Red Korb      918773             107         Camerata Dr  961388910
1  99716  Miranda Priestly      202298            1883          Golden Ave  987756388
2  90700     Regina George      291182             332           Maple Ave  337169072

In [ ]:
%%sql

SELECT person_id, event_name, COUNT(3) AS event_count
FROM facebook_event_checkin
WHERE person_id = 78881 OR person_id = 99716 OR person_id = 90700
GROUP BY person_id, event_name

   person_id            event_name  event_count
0      99716  SQL Symphony Concert            3